### ISSUE TITLE
Cannot reproduce the results

### ISSUE THREAD

**Issue by Boltzmachine** [PhyScene/PhyScene#4]
I downloaded the preprocessed dataset and the model weights `living_room` and run `test_livingroom.sh`, getting the following results

```
collision type rotated_bbox
box_box_collision_rate: 0.38532111048698425
livingroom.json
CKL: 2.1727645445539556
livingroom.json
2.1727645445539556
walkable_average_rate: 0.9775561168210295
accessable_rate: 0.0
accessable_handle_rate: 0.0
box_wall_rate: 0.78044922492882
```

looks like the collision rate (0.385) is far higher than it is reported in the paper (0.191). Is there any thought?

**Comment by YandanYang** [comment]
There might be something wrong with the config or preprocessed data, since the CKL is also beyond the normal range. Can you print out the config?

**Comment by Boltzmachine** [comment]
Thanks for replying. I use the default config file, changing some paths. One important change is that I prepend "cached" before `dataset_type` and `encoding_type` because I want to use the preprocessed dataset.


```yaml
# scene_livingroom.yaml
name: scene_synthesis

path_to_pickled_3d_futute_models: "data/pickled_data/threed_future_model_livingroom.pkl"

train:
  splits: ["train", "val"]
  batch_size: 128
  num_workers: 4
  num_epochs: 200000
  log_step: 100
  log_epoch: 1
  save_frequency: 2000
  max_grad_norm: 10
  # optimizer
  optimizer: Adam
  weight_decay: 0.0
  # schedule
  schedule: 'step'
  lr: 0.0002
  lr_step: 20000
  lr_decay: 0.5


test:
  splits: ["test"]
  batch_size: 128
  num_workers: 4
  frequency: 10
  num_step: 1

## dataset
dataset:
  name: ThreedFront
  max_length: 21
  class_num: 25 #21 original +1 empty
  use_feature: true
  feature_dim: 32
  desc: '[ThreedFront] -- dataset used for scene synthesis'
  frame_interval_train: 1
  frame_interval_test: 10
  use_color: true
  use_normal: false
  room_side: 6.2
  dataset_filtering: threed_front_livingroom
  dataset_directory: "data/preprocessed_data/LivingRoom/"
  dataset_type: "cached_threedfront_objfeats_lat32"
  encoding_type: "cached_diffusion_cosin_angle_objfeatsnorm_wocm_lat32"
  annotation_file: "configs/data/livingroom_threed_front_splits.csv"
  path_to_invalid_scene_ids: "configs/data/invalid_threed_front_rooms.txt"
  path_to_invalid_bbox_jids: "configs/data/black_list.txt"
  augmentations: ["rotations"] #["rotations","flip"] # ["fixed_rotations"]
  filter_fn: "threed_front_livingroom"  #"no_filtering"
  train_stats: "dataset_stats.txt"
  path_to_bounds: "data/bounds.npz"
  room_layout_size: "64,64"
  path_to_room_masks_dir: "data/room_mask"
  without_lamps: false
  # use_normalize: true

## for visualization
visualizer:
  name: SceneVisualizer
  vis_case_num: 32 # default is 32
  ksample: 1 # sample k case in each case
  vis_denoising: false # visualize denoising process
  save_mesh: false
  ## visualization config used in training
  visualize: false
  interval: 1
  window_size : "256,256"
  up_vector : "0,0,-1" #"0,1,0"
  camera_target : "0.0,0.0,0.0"
  camera_position :  "0,15,0"
  light : "-0.10923499,1.9325259,-7.19009"
  # background: "0.5,0.5,0.5,0.5" #"0,0,0,1" #"0.5,0.5,0.5,0.5"
  with_rotating_camera: false
  n_frames: 360
  save: false


## for quantitative evaluation
evaluator:
  name: SceneCKLEval
  eval_in_train: true
  ksample: 1000 # sample k case in each case
  ## evaluation config
  interval: 2000
  log_step: 100
  n_synthesized_scenes: 1000
  CKL_In_train: true
  weight_file: "outputs/livingroom_1205/model_134000"


network:
    type: "diffusion_scene_layout_ddpm"
    # denoising network
    net_type: "unet1d"
    optimizer: None

    # concate squarewish layer
    point_dim: 65 #29
    latent_dim: 512 #512
    room_mask_condition: true # not use room_mask
    sample_num_points: 21 # max_length

    objectness_dim: 0
    class_dim: 25  #24+1
    angle_dim: 2
    objfeat_dim: 32

    # class condition
    learnable_embedding: true
    instance_condition: true
    instance_emb_dim: 128
    # class_condition: false
    # class_emb_dim: 128

    # diffusion config
    diffusion_kwargs:
        schedule_type: 'linear'
        beta_start: 0.0001
        beta_end: 0.02
        time_num: 1000
        loss_type: 'mse'
        model_mean_type: 'eps'
        model_var_type: 'fixedsmall'
        loss_separate: true
        loss_iou: true
        train_stats_file: "data/preprocessed_data/LivingRoom/dataset_stats.txt"

    net_kwargs:
        dim: 512
        dim_mults: [1, 1, 1, 1]
        channels: 65
        objectness_dim: 0
        objfeat_dim: 32
        class_dim: 25
        angle_dim: 2
        context_dim: 512 # 512
        instanclass_dim: 128
        seperate_all: true  # separate all
        # self_condition: true
        # merge_bbox: true
        # modulate_time_context_instanclass: tru
```


```yaml
#default.yaml
hydra:
  run:
    dir: ${exp_dir}
  output_subdir: null

defaults:
  - _self_
  - task: scene_bedroom
  - optimizer: null

output_dir: outputs
exp_name: debug

continue_train: false
continue_epoch: 0
continue_from_weight: null

exp_dir: ${output_dir}/${now:%m-%d_%H-%M-%S}_${exp_name}
tb_dir: ${exp_dir}/tb_logs
vis_dir: ${exp_dir}/visual
ckpt_dir: ${exp_dir}/ckpts

gpu: 0

## for saving model
save_model_interval: 2000
save_model_seperately: true
save_scene_model: false # save scene model or not

feature_extractor:
    name: "resnet18"
    freeze_bn: true
    input_channels: 1
    feature_size: 64

clip_denoised: false


BASE_DIR: ./
PATH_TO_SCENES: "data/threed_front.pkl"

3DFRONT_dir: data
path_to_floor_plan_textures: "demo/floor_plan_texture_images"
no_texture: false
dataset:
# for object autoencoder
  # dataset_directory: ${3DFRONT_dir}/3D-FRONT/
  path_to_3d_front_dataset_directory: ${3DFRONT_dir}/3D-FRONT
  path_to_3d_future_dataset_directory: ${3DFRONT_dir}/3D-FUTURE-model
  path_to_models : ${3DFRONT_dir}/3D-FUTURE-model
  path_to_model_info: ${3DFRONT_dir}/3D-FUTURE-model/model_info.json

ai2thor:
  path_to_ai2thor: /home/yandan/workspace/ai2thor/ExportedObj-room-rightxyz #_blender_convert
  path_to_center_info: /home/yandan/workspace/PhyScene/ai2thor/center.json
  path_to_mask: /home/yandan/workspace/PhyScene/ai2thor/mask
  path_to_result: /home/yandan/workspace/PhyScene/ai2thor/generate_bbox

ThreeDFRONT:
  path_to_result: /home/yandan/workspace/PhyScene/3D_front/generate_filterGPN_clean


GAPartNet:
  pickled_GPN_dir: "/home/yandan/workspace/GAPartNet/dataset"
  GPN_open_ratio: "/home/yandan/workspace/Scene-Diffuser-New/data/GPN_open_ratio.json"
  GPN_good_idx: "/home/yandan/workspace/Scene-Diffuser-New/data/GPN_good_idx.json"
  path_to_models: "/home/yandan/dataset/partnet_mobility_part/"
  ID_PATH: '/home/yandan/workspace/GAPartNet/dataset/render_tools/meta/partnet_all_id_list.txt'


logger:
    type: "wandb"
    project: "physcene"

evaluation:
  overlap_type: "rotated_bbox"
  generate_result_json: true
  gapartnet: true
  jsonname: "debug.json"
  load_result: false
  save_result: true
  visual: false
  render2img: false
  without_floor: false
  save_mesh: false
  save_walkable_map: false
  render_save_path: "result_render/debug

```
